# start by pulling the python image
FROM python:3.9-alpine

# copy the requirements file into the image
COPY ./requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /app

# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

# copy every content from the local file to the image
COPY . /app

# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]

# 执行安装 Python 环境依赖
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple gunicorn gevent
RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple flask

# 暴露 80 端口，给外部使用，因为上面我们开启的是 80 端口
EXPOSE 5000

# 使用 gunicorn 运行 Flask 项目，最后一个命令： app:app  前者对应的是flask 启动 文件，后面不要乱改
CMD gunicorn  -c gun.conf app:app